steps:
  - name: "node"
    entrypoint: "ls"
    args: ["-a"]

  - name: "node"
    entrypoint: "npm"
    args: ["i"]

  - name: "node"
    entrypoint: "npm"
    args: ["install -y envsub"]
  - name: "node"
    entrypoint: "npx"
    args:
      [
        '-e accessKeyTemplate="$accessKey"',
        '-e secretKeyTemplate="$secretKey" ',
        '-e deviceIdTemplate="$deviceId"',
        ".env.template .env",
      ]

  - name: "node"
    entrypoint: "npm"
    args: ["run", "start"]
options:
  logging: CLOUD_LOGGING_ONLY
