steps:
  - name: "node"
    entrypoint: "ls"
    id: "Debugging showing files"
    args: ["-a"]

  - name: "node"
    entrypoint: "npm"
    id: "installing dependencies"
    args: ["i"]

  - name: "node"
    entrypoint: "npm"
    args: ["install", "envsub"]
  - name: "node"
    entrypoint: "npx"
    id: "filling env file with template secrets"
    args:
      [
        "envsub",
        "-e",
        'accessKeyTemplate="$accessKey"',
        "-e",
        'secretKeyTemplate="$secretKey" ',
        "-e",
        'deviceIdTemplate="$deviceId"',
        ".env.template",
        ".env",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args: ["run", "deploy", "--source", "."]
    id: Deploy
    entrypoint: gcloud
  #- name: "node"
  #  entrypoint: "npm"
  #  args: ["run", "start"]
options:
  logging: CLOUD_LOGGING_ONLY
